07-04 17:53:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
SELECT * FROM MEMBER [42102-167]
07-04 17:53:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:

      INSERT INTO MEMBER (
        NAME,
        DESCRIPTION,
        BIRTHDAY,
        CREATED_AT
      ) VALUES (
        ?,
        ?,
        ?,
        ?
      )
       [42102-167]
07-04 17:53:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:

      INSERT INTO MEMBER (
        NAME,
        DESCRIPTION,
        BIRTHDAY,
        CREATED_AT
      ) VALUES (
        ?,
        ?,
        ?,
        ?
      )
       [42102-167]
07-04 17:53:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UN_NORMALIZED" not found; SQL statement:
select count(1) from un_normalized [42102-167]
07-04 17:53:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 17:53:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 17:53:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
SELECT * FROM MEMBER WHERE name = ? [42102-167]
07-04 17:53:02 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at scalikejdbc.CommonsConnectionPool.borrow(ConnectionPool.scala:215)
	at scalikejdbc.ConnectionPool$.borrow(ConnectionPool.scala:122)
	at scalikejdbc.DB$.readOnlyWithConnection(DB.scala:132)
	at scalikejdbc.mapper.Model.table(Model.scala:39)
	at MapperGeneratorSpec$$anonfun$2.apply$mcV$sp(MapperGeneratorSpec.scala:114)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2987)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1994)
	at MapperGeneratorSpec.withFixture(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2984)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:228)
	at org.scalatest.FlatSpec$class.runTest(FlatSpec.scala:2993)
	at MapperGeneratorSpec.runTest(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:300)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:288)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:288)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:283)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:373)
	at org.scalatest.FlatSpec$class.runTests(FlatSpec.scala:3055)
	at MapperGeneratorSpec.runTests(MapperGeneratorSpec.scala:7)
	at org.scalatest.Suite$class.run(Suite.scala:2321)
	at MapperGeneratorSpec.org$scalatest$FlatSpec$$super$run(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:411)
	at org.scalatest.FlatSpec$class.run(FlatSpec.scala:3102)
	at MapperGeneratorSpec.run(MapperGeneratorSpec.scala:7)
	at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:217)
	at org.scalatools.testing.Runner2.run(Runner2.java:16)
	at sbt.TestRunner.delegateRun(TestFramework.scala:62)
	at sbt.TestRunner.run(TestFramework.scala:56)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:196)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 78 more
07-04 17:53:02 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at scalikejdbc.CommonsConnectionPool.borrow(ConnectionPool.scala:215)
	at scalikejdbc.ConnectionPool$.borrow(ConnectionPool.scala:122)
	at scalikejdbc.DB$.readOnlyWithConnection(DB.scala:132)
	at scalikejdbc.mapper.Model.table(Model.scala:39)
	at MapperGeneratorSpec$$anonfun$2.apply$mcV$sp(MapperGeneratorSpec.scala:114)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2987)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1994)
	at MapperGeneratorSpec.withFixture(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2984)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:228)
	at org.scalatest.FlatSpec$class.runTest(FlatSpec.scala:2993)
	at MapperGeneratorSpec.runTest(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:300)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:288)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:288)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:283)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:373)
	at org.scalatest.FlatSpec$class.runTests(FlatSpec.scala:3055)
	at MapperGeneratorSpec.runTests(MapperGeneratorSpec.scala:7)
	at org.scalatest.Suite$class.run(Suite.scala:2321)
	at MapperGeneratorSpec.org$scalatest$FlatSpec$$super$run(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:411)
	at org.scalatest.FlatSpec$class.run(FlatSpec.scala:3102)
	at MapperGeneratorSpec.run(MapperGeneratorSpec.scala:7)
	at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:217)
	at org.scalatools.testing.Runner2.run(Runner2.java:16)
	at sbt.TestRunner.delegateRun(TestFramework.scala:62)
	at sbt.TestRunner.run(TestFramework.scala:56)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:196)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 78 more
07-04 17:53:02 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Table "WITHOUT_PK" not found; SQL statement:
select count(1) from without_pk [42102-167]
07-04 18:00:34 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
select count(1) from member [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:

      INSERT INTO MEMBER (
        NAME,
        DESCRIPTION,
        BIRTHDAY,
        CREATED_AT
      ) VALUES (
        ?,
        ?,
        ?,
        ?
      )
       [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:

      INSERT INTO MEMBER (
        NAME,
        DESCRIPTION,
        BIRTHDAY,
        CREATED_AT
      ) VALUES (
        ?,
        ?,
        ?,
        ?
      )
       [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 18:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MEMBER" not found; SQL statement:
INSERT INTO MEMBER ( NAME, DESCRIPTION, BIRTHDAY, CREATED_AT ) VALUES ( ?, ?, ?, ? ) [42102-167]
07-04 18:04:42 jdbc[6]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at scalikejdbc.CommonsConnectionPool.borrow(ConnectionPool.scala:215)
	at scalikejdbc.ConnectionPool$.borrow(ConnectionPool.scala:122)
	at scalikejdbc.DB$.readOnlyWithConnection(DB.scala:132)
	at scalikejdbc.mapper.Model.table(Model.scala:39)
	at MapperGeneratorSpec$$anonfun$2.apply$mcV$sp(MapperGeneratorSpec.scala:114)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2987)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1994)
	at MapperGeneratorSpec.withFixture(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2984)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:228)
	at org.scalatest.FlatSpec$class.runTest(FlatSpec.scala:2993)
	at MapperGeneratorSpec.runTest(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:300)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:288)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:288)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:283)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:373)
	at org.scalatest.FlatSpec$class.runTests(FlatSpec.scala:3055)
	at MapperGeneratorSpec.runTests(MapperGeneratorSpec.scala:7)
	at org.scalatest.Suite$class.run(Suite.scala:2321)
	at MapperGeneratorSpec.org$scalatest$FlatSpec$$super$run(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:411)
	at org.scalatest.FlatSpec$class.run(FlatSpec.scala:3102)
	at MapperGeneratorSpec.run(MapperGeneratorSpec.scala:7)
	at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:217)
	at org.scalatools.testing.Runner2.run(Runner2.java:16)
	at sbt.TestRunner.delegateRun(TestFramework.scala:62)
	at sbt.TestRunner.run(TestFramework.scala:56)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:196)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 78 more
07-04 18:04:42 jdbc[6]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:174)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at scalikejdbc.CommonsConnectionPool.borrow(ConnectionPool.scala:215)
	at scalikejdbc.ConnectionPool$.borrow(ConnectionPool.scala:122)
	at scalikejdbc.DB$.readOnlyWithConnection(DB.scala:132)
	at scalikejdbc.mapper.Model.table(Model.scala:39)
	at MapperGeneratorSpec$$anonfun$2.apply$mcV$sp(MapperGeneratorSpec.scala:114)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at MapperGeneratorSpec$$anonfun$2.apply(MapperGeneratorSpec.scala:65)
	at org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2987)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1994)
	at MapperGeneratorSpec.withFixture(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2984)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2993)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:228)
	at org.scalatest.FlatSpec$class.runTest(FlatSpec.scala:2993)
	at MapperGeneratorSpec.runTest(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3055)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:300)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:288)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:288)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:283)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:373)
	at org.scalatest.FlatSpec$class.runTests(FlatSpec.scala:3055)
	at MapperGeneratorSpec.runTests(MapperGeneratorSpec.scala:7)
	at org.scalatest.Suite$class.run(Suite.scala:2321)
	at MapperGeneratorSpec.org$scalatest$FlatSpec$$super$run(MapperGeneratorSpec.scala:7)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3102)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:411)
	at org.scalatest.FlatSpec$class.run(FlatSpec.scala:3102)
	at MapperGeneratorSpec.run(MapperGeneratorSpec.scala:7)
	at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:217)
	at org.scalatools.testing.Runner2.run(Runner2.java:16)
	at sbt.TestRunner.delegateRun(TestFramework.scala:62)
	at sbt.TestRunner.run(TestFramework.scala:56)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:196)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:113)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-167]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 78 more
